### ISSUE TITLE
mvn clean package -DskipTests执行会报错

### ISSUE THREAD

**Issue by root13920** [su18/ysoserial#11]
![image](https://user-images.githubusercontent.com/54227193/216528842-74f23995-85e1-455f-9c8d-c088b8878b1b.png)

**Comment by su18** [comment]
把目录下 lib 文件夹加在项目的 Libraries 中试试

**Comment by root13920** [comment]
Libraries 是哪里

**Comment by su18** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/30317673/216862741-4535125c-8aa0-4190-ac87-e7d952cbe8c2.png">

**Comment by root13920** [comment]
> 

感谢，虽然当时我还是编译不了 ...  o_0

**Comment by root13920** [comment]
![image](https://user-images.githubusercontent.com/54227193/217138182-990435d7-c8f8-4af3-b00d-2b11f7e0011b.png)

**Comment by kN6jq** [comment]
> ![image](https://user-images.githubusercontent.com/54227193/217138182-990435d7-c8f8-4af3-b00d-2b11f7e0011b.png)

使用mvn将jar导入到本地仓库中 直接编译即可
mvn install:install-file -Dfile="F:\OneDrive\tools\java\su18ysoserial\lib\com.springsource.javax.media.jai.core-1.1.3.jar" -DgroupId="jai-core" -DartifactId="jai-core" -Dversion="0.01" -Dpackaging=jar

mvn install:install-file -Dfile="F:\OneDrive\tools\java\su18ysoserial\lib\jai-codec-1.1.3.jar" -DgroupId="jai-codec" -DartifactId="jai-codec" -Dversion="0.01" -Dpackaging=jar

![image](https://user-images.githubusercontent.com/27048404/217151793-82f0f855-5bfa-4a54-ae81-50d9cb6e65cb.png)

**Comment by root13920** [comment]
可以了可以了  感谢大佬  非常哇塞
![image](https://user-images.githubusercontent.com/54227193/217154043-c62c669e-c6a2-4963-815b-3e2ff7fcde39.png)
