### ISSUE TITLE
帮助信息优化

### ISSUE THREAD

**Issue by DongHuangT1** [su18/ysoserial#12]
参数部分有点堆积，查看有点不太方便

![image](https://user-images.githubusercontent.com/51707652/222632772-0e5ab4d2-24a1-4038-9e1f-b2d4d5032562.png)

**Comment by su18** [comment]
https://github.com/su18/ysoserial/commit/710a2aea924e809efbabe1b227881d28a97851a1

更新 HelpFormatter 以执行终端大小动态调整，最大宽度 200
