### ISSUE TITLE
LF自定义执行类小问题

### ISSUE THREAD

**Issue by qing-root** [su18/ysoserial#5]
原本代码使用LF功能貌似是有问题的，这里读取需要自定义类名会直接异常
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/30001685/191310166-0fd6fc58-690e-4ea2-b2df-53ba0a8be930.png">

修改：
```
//String className = command.split("[-]")[1];
			String[] temp = command.split("[/]");
			String fileName = temp[temp.length-1];
			String className = fileName.split("[.]")[0];
```
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/30001685/191312915-8be3eaa9-11b8-4c5d-ab25-d1431bc05136.png">

**Comment by su18** [comment]
加载本地 class 文件使用 “ LF-本地文件路径-类名 ” 的格式，例如 LF-/tmp/aaa-org.su18.Evil
由于为了 “反射调用 native 方法”、“恶意类指定包名” 等目标，使用了指定包名的方式进行类加载

ReadMe 中未及时更新，现已经修改
https://github.com/su18/ysoserial/commit/4888f68782953c98de09f81f44f563d9c0cc1376
