### ISSUE TITLE
Spring无法生成

### ISSUE THREAD

**Issue by DongHuangT1** [su18/ysoserial#6]
![image](https://user-images.githubusercontent.com/51707652/195005840-a1a63378-0fdd-46ff-a546-717cd0bffd7c.png)

**Comment by su18** [comment]
已修复，现使用 4.1.4.RELEASE 作为 Spring 依赖包版本，请使用最新代码重新 Build

https://github.com/su18/ysoserial/commit/75868fb76df032f115167bb30f5fe3bcbeefc9a6
