### ISSUE TITLE
本地环境:java15+Windows ，使用下面命令报错

### ISSUE THREAD

**Issue by zoceanyq** [su18/ysoserial#7]
![QQ图片20221031163101](https://user-images.githubusercontent.com/97746429/198965324-504f0be0-a882-4d13-9c20-22167cb9cfae.png)

**Comment by su18** [comment]
1. 请使用 JDK 8，高版本 JDK 暂不支持
2. 部分 payload 使用反射调用底层的类可能在 windows 上不存在，将会在修复后关闭此 issues

**Comment by su18** [comment]
[修复混淆版命令执行在 windows 上的失效问题。](https://github.com/su18/ysoserial/commit/22154325dbe959bb8920d40bfe3ec799da9734b2)
