### ISSUE TITLE
idea编译出现attrNS1.setValues  找不到符号错误

### ISSUE THREAD

**Issue by 3t2ugg1e** [su18/ysoserial#8]
通过IDEA进行编译，出现attrNS1.setValues 找不到符号错误
<img width="960" alt="image" src="https://user-images.githubusercontent.com/62066043/211961850-ca872e71-6259-4553-843a-b263575c5f4a.png">
jre/lib/rt.jar!/com/sun/org/apache/xerces/internal/dom/AttrNSImpl.class
初步定位是jdk版本的问题，于是切换8u20、8u141、8u333等多个jdk版本，发现8u333不存在AttrNSImpl.setValues方法，8u20和8u141存在，但是以上版本均无法正常打包，请问大佬您的设置是什么？怎么打包的？
<img width="334" alt="image" src="https://user-images.githubusercontent.com/62066043/211962103-49f0ad39-d5ed-4c0c-8d5c-4d766b84fc1b.png">

**Comment by su18** [comment]
这个应该是 JDK 的问题，com.sun 开头的包被认为是可能随时删减、不进行前后兼容的包，只存在部分 JDK 中。
我建议是日常不使用 OpenJDK，更换使用其他较完整的发行版 JDK，如 oracle、azul 等

**Comment by 3t2ugg1e** [comment]
我切换过Oracle OpenJDK 8u20、8u141、8u333和azul JDK 8u345（应该与您JDK版本一致）、8u352等版本进行编译，但仍出现同样“错误：找不到符号”的问题。实在没法解决该问题了 :(

**Comment by su18** [comment]
加我微信，1对1手把手解决问题，上门服务，品质保障

**Comment by su18** [comment]
最终确认是配置问题，使用指定版本的 JDK 和 Maven 即可打包，由于 IDEA 有各种 BUG，可以使用命令行
