### ISSUE TITLE
DL参数好像有点问题

### ISSUE THREAD

**Issue by f0ng** [su18/ysoserial#9]
最新版本
正常情况下，`-g xxx -p "open -a Calculator.app"`是可以利用的
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/48286013/212275318-4f63667d-9adc-4a94-97d0-2afca79b1d9e.png">

反序列化直接可以打开计算器
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/48286013/212275642-61690d6d-7f2d-4492-bb1c-f00e8897fe38.png">

但是加上`-g xxx -p "DL-xxxxxx.dnslog"`参数，这样序列化不能发起dns请求，不知道是不是我用法的问题，试了1.2版本、0.9版本都不行，本地可以发起dns请求的
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/48286013/212275881-ce49b1f8-7e24-419e-b6ed-80ec1dda2024.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/48286013/212275921-a6d66c53-af0d-478e-a073-d81c8fae9c7d.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/48286013/212275963-3e8dd5f7-efd1-4aa7-94c0-5a3ae8194ec4.png">

**Comment by su18** [comment]
DL- 参数针对使用 Transformer[] 的 CC 链，看你的截图用的好像是 CB

**Comment by f0ng** [comment]
感谢师傅解答~
